// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tx.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MultiTransactionBody;
@class MultiTransactionInput;
@class MultiTransactionNode;
@class MultiTransactionOutput;
@class MultiTransactionSignature;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - TxRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface TxRoot : GPBRootObject
@end

#pragma mark - MultiTransaction

typedef GPB_ENUM(MultiTransaction_FieldNumber) {
  MultiTransaction_FieldNumber_TxHash = 1,
  MultiTransaction_FieldNumber_TxBody = 2,
  MultiTransaction_FieldNumber_Status = 3,
  MultiTransaction_FieldNumber_TxNode = 4,
  MultiTransaction_FieldNumber_Result = 5,
};

@interface MultiTransaction : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *txHash;

@property(nonatomic, readwrite, strong, null_resettable) MultiTransactionBody *txBody;
/** Test to see if @c txBody has been set. */
@property(nonatomic, readwrite) BOOL hasTxBody;

@property(nonatomic, readwrite, copy, null_resettable) NSString *status;

@property(nonatomic, readwrite, strong, null_resettable) MultiTransactionNode *txNode;
/** Test to see if @c txNode has been set. */
@property(nonatomic, readwrite) BOOL hasTxNode;

@property(nonatomic, readwrite, copy, null_resettable) NSData *result;

@end

#pragma mark - MultiTransactionBody

typedef GPB_ENUM(MultiTransactionBody_FieldNumber) {
  MultiTransactionBody_FieldNumber_InputsArray = 1,
  MultiTransactionBody_FieldNumber_OutputsArray = 2,
  MultiTransactionBody_FieldNumber_Exdata = 3,
  MultiTransactionBody_FieldNumber_SignaturesArray = 4,
  MultiTransactionBody_FieldNumber_DelegateArray = 5,
  MultiTransactionBody_FieldNumber_Data_p = 6,
  MultiTransactionBody_FieldNumber_Timestamp = 7,
  MultiTransactionBody_FieldNumber_Type = 8,
};

@interface MultiTransactionBody : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MultiTransactionInput*> *inputsArray;
/** The number of items in @c inputsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger inputsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MultiTransactionOutput*> *outputsArray;
/** The number of items in @c outputsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger outputsArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSData *exdata;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MultiTransactionSignature*> *signaturesArray;
/** The number of items in @c signaturesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger signaturesArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSData*> *delegateArray;
/** The number of items in @c delegateArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger delegateArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite) int32_t type;

@end

#pragma mark - MultiTransactionInput

typedef GPB_ENUM(MultiTransactionInput_FieldNumber) {
  MultiTransactionInput_FieldNumber_Nonce = 1,
  MultiTransactionInput_FieldNumber_Address = 4,
  MultiTransactionInput_FieldNumber_Amount = 5,
  MultiTransactionInput_FieldNumber_Token = 7,
  MultiTransactionInput_FieldNumber_Symbol = 8,
  MultiTransactionInput_FieldNumber_CryptoToken = 9,
};

@interface MultiTransactionInput : GPBMessage

@property(nonatomic, readwrite) int32_t nonce;

@property(nonatomic, readwrite, copy, null_resettable) NSData *address;

@property(nonatomic, readwrite, copy, null_resettable) NSData *amount;

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

@property(nonatomic, readwrite, copy, null_resettable) NSData *cryptoToken;

@end

#pragma mark - MultiTransactionOutput

typedef GPB_ENUM(MultiTransactionOutput_FieldNumber) {
  MultiTransactionOutput_FieldNumber_Address = 1,
  MultiTransactionOutput_FieldNumber_Amount = 2,
  MultiTransactionOutput_FieldNumber_Symbol = 3,
  MultiTransactionOutput_FieldNumber_CryptoToken = 4,
};

@interface MultiTransactionOutput : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *address;

@property(nonatomic, readwrite, copy, null_resettable) NSData *amount;

@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

@property(nonatomic, readwrite, copy, null_resettable) NSData *cryptoToken;

@end

#pragma mark - MultiTransactionSignature

typedef GPB_ENUM(MultiTransactionSignature_FieldNumber) {
  MultiTransactionSignature_FieldNumber_Signature = 1,
};

@interface MultiTransactionSignature : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *signature;

@end

#pragma mark - MultiTransactionNode

typedef GPB_ENUM(MultiTransactionNode_FieldNumber) {
  MultiTransactionNode_FieldNumber_Node = 1,
  MultiTransactionNode_FieldNumber_Address = 2,
  MultiTransactionNode_FieldNumber_Bcuid = 3,
};

@interface MultiTransactionNode : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *node;

@property(nonatomic, readwrite, copy, null_resettable) NSData *address;

@property(nonatomic, readwrite, copy, null_resettable) NSString *bcuid;

@end

#pragma mark - BroadcastTransactionMsg

typedef GPB_ENUM(BroadcastTransactionMsg_FieldNumber) {
  BroadcastTransactionMsg_FieldNumber_TxHashArray = 1,
  BroadcastTransactionMsg_FieldNumber_TxDatasArray = 2,
};

@interface BroadcastTransactionMsg : GPBMessage

/** repeated string txHexStr = 1; */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSData*> *txHashArray;
/** The number of items in @c txHashArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger txHashArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSData*> *txDatasArray;
/** The number of items in @c txDatasArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger txDatasArray_Count;

@end

#pragma mark - CryptoTokenData

typedef GPB_ENUM(CryptoTokenData_FieldNumber) {
  CryptoTokenData_FieldNumber_Total = 1,
  CryptoTokenData_FieldNumber_Symbol = 2,
  CryptoTokenData_FieldNumber_ExtData = 3,
  CryptoTokenData_FieldNumber_NameArray = 4,
  CryptoTokenData_FieldNumber_CodeArray = 5,
};

@interface CryptoTokenData : GPBMessage

@property(nonatomic, readwrite) int64_t total;

@property(nonatomic, readwrite, copy, null_resettable) NSString *symbol;

@property(nonatomic, readwrite, copy, null_resettable) NSData *extData;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *nameArray;
/** The number of items in @c nameArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger nameArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *codeArray;
/** The number of items in @c codeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger codeArray_Count;

@end

#pragma mark - UnionAccountData

typedef GPB_ENUM(UnionAccountData_FieldNumber) {
  UnionAccountData_FieldNumber_Max = 1,
  UnionAccountData_FieldNumber_AcceptMax = 2,
  UnionAccountData_FieldNumber_AcceptLimit = 3,
  UnionAccountData_FieldNumber_AddressArray = 4,
};

@interface UnionAccountData : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *max;

@property(nonatomic, readwrite, copy, null_resettable) NSData *acceptMax;

@property(nonatomic, readwrite) int32_t acceptLimit;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSData*> *addressArray;
/** The number of items in @c addressArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger addressArray_Count;

@end

#pragma mark - SanctionData

typedef GPB_ENUM(SanctionData_FieldNumber) {
  SanctionData_FieldNumber_Content = 1,
  SanctionData_FieldNumber_EndBlockHeight = 2,
  SanctionData_FieldNumber_Result = 3,
};

@interface SanctionData : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *content;

@property(nonatomic, readwrite) int64_t endBlockHeight;

@property(nonatomic, readwrite, copy, null_resettable) NSData *result;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
